// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeGestionTalento.Infrastructure.Data;

#nullable disable

namespace SistemaDeGestionTalento.Infrastructure.Migrations
{
    [DbContext(typeof(SgiDbContext))]
    partial class SgiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Certificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Entidad")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FechaObtencion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("certificaciones");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.ColaboradorSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EvaluadorId")
                        .HasColumnType("int")
                        .HasColumnName("evaluador_id");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_evaluacion");

                    b.Property<int>("NivelId")
                        .HasColumnType("int")
                        .HasColumnName("nivel_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("EvaluadorId");

                    b.HasIndex("NivelId");

                    b.HasIndex("SkillId");

                    b.HasIndex("UsuarioId", "SkillId")
                        .IsUnique();

                    b.ToTable("colaboradores_skills");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.KpiLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreKpi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric(10, 2)");

                    b.HasKey("Id");

                    b.ToTable("kpi_logs");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.LiderColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<int>("LiderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColaboradorId");

                    b.HasIndex("LiderId", "ColaboradorId")
                        .IsUnique();

                    b.ToTable("lider_colaborador");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Matching", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Porcentaje")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("VacanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VacanteId");

                    b.ToTable("matching");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.NivelSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("niveles_skill");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Leido")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("VacanteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VacanteId");

                    b.ToTable("notificaciones");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("skills");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.UrgenciaVacante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("urgencias_vacante");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContraseñaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contraseña_hash");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Disponibilidad")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PuestoActual")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("puesto_actual");

                    b.Property<int>("RolId")
                        .HasColumnType("int")
                        .HasColumnName("rol_id");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Vacante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaInicioRequerida")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_inicio_requerida");

                    b.Property<int>("LiderId")
                        .HasColumnType("int")
                        .HasColumnName("lider_id");

                    b.Property<string>("Proyecto")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("UrgenciaId")
                        .HasColumnType("int")
                        .HasColumnName("urgencia_id");

                    b.HasKey("Id");

                    b.HasIndex("LiderId");

                    b.HasIndex("UrgenciaId");

                    b.ToTable("vacantes");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.VacanteSkill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("NivelId")
                        .HasColumnType("int")
                        .HasColumnName("nivel_id");

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnName("skill_id");

                    b.Property<int>("VacanteId")
                        .HasColumnType("int")
                        .HasColumnName("vacante_id");

                    b.HasKey("Id");

                    b.HasIndex("NivelId");

                    b.HasIndex("SkillId");

                    b.HasIndex("VacanteId", "SkillId")
                        .IsUnique();

                    b.ToTable("vacante_skills");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Certificacion", b =>
                {
                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Usuario", "Usuario")
                        .WithMany("Certificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.ColaboradorSkill", b =>
                {
                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Usuario", "Evaluador")
                        .WithMany("SkillsEvaluados")
                        .HasForeignKey("EvaluadorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaDeGestionTalento.Core.Entities.NivelSkill", "NivelSkill")
                        .WithMany()
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Skill", "Skill")
                        .WithMany("ColaboradorSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Usuario", "Usuario")
                        .WithMany("ColaboradorSkills")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluador");

                    b.Navigation("NivelSkill");

                    b.Navigation("Skill");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.LiderColaborador", b =>
                {
                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Usuario", "Colaborador")
                        .WithMany("LideresAsignados")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Usuario", "Lider")
                        .WithMany("ColaboradoresAsignados")
                        .HasForeignKey("LiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Colaborador");

                    b.Navigation("Lider");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Matching", b =>
                {
                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Usuario", "Usuario")
                        .WithMany("Matchings")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Vacante", "Vacante")
                        .WithMany("Matchings")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Notificacion", b =>
                {
                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Vacante", "Vacante")
                        .WithMany("Notificaciones")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Vacante", b =>
                {
                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Usuario", "Lider")
                        .WithMany("VacantesCreadas")
                        .HasForeignKey("LiderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaDeGestionTalento.Core.Entities.UrgenciaVacante", "UrgenciaVacante")
                        .WithMany()
                        .HasForeignKey("UrgenciaId");

                    b.Navigation("Lider");

                    b.Navigation("UrgenciaVacante");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.VacanteSkill", b =>
                {
                    b.HasOne("SistemaDeGestionTalento.Core.Entities.NivelSkill", "NivelSkill")
                        .WithMany()
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Skill", "Skill")
                        .WithMany("VacanteSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeGestionTalento.Core.Entities.Vacante", "Vacante")
                        .WithMany("VacanteSkills")
                        .HasForeignKey("VacanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelSkill");

                    b.Navigation("Skill");

                    b.Navigation("Vacante");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Skill", b =>
                {
                    b.Navigation("ColaboradorSkills");

                    b.Navigation("VacanteSkills");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Usuario", b =>
                {
                    b.Navigation("Certificaciones");

                    b.Navigation("ColaboradorSkills");

                    b.Navigation("ColaboradoresAsignados");

                    b.Navigation("LideresAsignados");

                    b.Navigation("Matchings");

                    b.Navigation("Notificaciones");

                    b.Navigation("SkillsEvaluados");

                    b.Navigation("VacantesCreadas");
                });

            modelBuilder.Entity("SistemaDeGestionTalento.Core.Entities.Vacante", b =>
                {
                    b.Navigation("Matchings");

                    b.Navigation("Notificaciones");

                    b.Navigation("VacanteSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
